version: '2'

services:
  hoopstakes:
    links:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/
    ports:
      - '1337:80'
    environment:
      - "PORT=80"
      - "DEBUG=hoopstakes:*"
      - "DEBUG_COLORS=true"
  db:
    image: mysql:5.7
    ports:
      - '3308:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hoopstakes